### PR TITLE
Show saved data

### PR DESCRIPTION
**Pull request by huonggiangbui**
Add functionality that show saved data

Command: 
`ovuli data`

image

### CODE REVIEW

**Comment by huonggiangbui** [comment]
@sarthology update my functionality. please check it out

**Comment by sarthology** [comment]
Add a gif or Picture

**Comment by huonggiangbui** [comment]
@sarthology the picture above isnt enough?

**Comment by sarthology** [comment]
Oh You have made some changes great. One more thing needed to be there. Join these separate boxes and make it one.

**Comment by huonggiangbui** [comment]
@sarthology you can check it again. All done

**Comment by sarthology** [comment]
Awesome !!

**Pull request merged**
